# Generated by Django 5.2.8 on 2025-11-06 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roommember',
            name='idx_room_members_user',
        ),
        migrations.RemoveIndex(
            model_name='roommemberslog',
            name='idx_rml_room_created',
        ),
        migrations.RemoveIndex(
            model_name='roommemberslog',
            name='idx_rml_user_created',
        ),
        migrations.RemoveIndex(
            model_name='roommemberslog',
            name='idx_rml_event_created',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='core_messag_room_id_727e5a_idx',
            old_name='idx_messages_room_created',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='core_messag_user_id_bc264d_idx',
            old_name='idx_messages_user_created',
        ),
        migrations.AlterField(
            model_name='roommemberslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
