# Generated by Django 5.2.8 on 2025-11-10 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_roommember_idx_room_members_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
