# Generated by Django 5.2.8 on 2025-11-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_roommember_is_admin_alter_roommember_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='roommember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
