# Generated by Django 5.2.8 on 2025-11-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_roommember_is_admin_roommember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='role',
        ),
        migrations.AddField(
            model_name='roommember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
